sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - 2.2.5
  - 2.3.1
  - 2.4.0
before_install: gem install bundler -v 1.14.5
branches:
  only:
    - master
notifications:
  email: false
