module TaiwanAddress
  class PostalCode
    # NOTE https://en.wikipedia.org/wiki/Postal_codes_in_Taiwan
    POSTAL_CODE_HASH = {
      # 1 – Taipei
      # Taipei City
      100 => "Zhongzheng District	中正區",
      103 => "Datong District	大同區",
      104 => "Zhongshan District	中山區",
      105 => "Songshan District	松山區",
      106 => "Da'an District	大安區",
      108 => "Wanhua District	萬華區",
      110 => "Xinyi District	信義區",
      111 => "Shilin District	士林區",
      112 => "Beitou District	北投區",
      114 => "Neihu District	內湖區",
      115 => "Nangang District	南港區",
      116 => "Wenshan District	文山區",
      # 2 – Keelung, New Taipei, Matsu, Yilan
      # Keelung City
      200 => "Ren'ai District	仁愛區",
      201 => "Xinyi District	信義區",
      202 => "Zhongzheng District	中正區",
      203 => "Zhongshan District	中山區",
      204 => "Anle District	安樂區",
      205 => "Nuannuan District	暖暖區",
      206 => "Qidu District	七堵區",
      # Lienchiang County (Matsu)
      209 => "Nangan Township	南竿鄉",
      210 => "Beigan Township	北竿鄉",
      211 => "Juguang Township	莒光鄉",
      212 => "Dongyin Township	東引鄉",
      # New Taipei City
      207 => "Wanli District	萬里區",
      208 => "Jinshan District	金山區",
      220 => "Banqiao District	板橋區",
      221 => "Xizhi District	汐止區",
      222 => "Shenkeng District	深坑區",
      223 => "Shiding District	石碇區",
      224 => "Ruifang District	瑞芳區",
      226 => "Pingxi District	平溪區",
      227 => "Shuangxi District	雙溪區",
      228 => "Gongliao District	貢寮區",
      231 => "Xindian District	新店區",
      232 => "Pinglin District	坪林區",
      233 => "Wulai District	烏來區",
      234 => "Yonghe District	永和區",
      235 => "Zhonghe District	中和區",
      236 => "Tucheng District	土城區",
      237 => "Sanxia District	三峽區",
      238 => "Shulin District	樹林區",
      239 => "Yingge District	鶯歌區",
      241 => "Sanchong District	三重區",
      242 => "Xinzhuang District	新莊區",
      243 => "Taishan District	泰山區",
      244 => "Linkou District	林口區",
      247 => "Luzhou District	蘆洲區",
      248 => "Wugu District	五股區",
      249 => "Bali District	八里區",
      251 => "Tamsui District	淡水區",
      252 => "Sanzhi District	三芝區",
      253 => "Shimen District	石門區",
      # Yilan County
      260 => "Yilan City	宜蘭市",
      261 => "Toucheng Township	頭城鎮",
      262 => "Jiaoxi Township	礁溪鄉",
      263 => "Zhuangwei Township	壯圍鄉",
      264 => "Yuanshan Township	員山鄉",
      265 => "Luodong Township	羅東鎮",
      266 => "Sanxing Township	三星鄉",
      267 => "Datong Township	大同鄉",
      268 => "Wujie Township	五結鄉",
      269 => "Dongshan Township	冬山鄉",
      270 => "Su'ao Township	蘇澳鎮",
      272 => "Nan'ao Township	南澳鄉",
      290 => "Diaoyutai Islands	釣魚台列嶼",

      # 3 – Hsinchu, Miaoli, Taoyuan
      # Hsinchu City
      300 => "East District	東區",
      300 => "North District	北區",
      300 => "Xiangshan District	香山區",
      # Hsinchu County
      302 => "Zhubei City	竹北市",
      303 => "Hukou Township	湖口鄉",
      304 => "Xinfeng Township	新豐鄉",
      305 => "Xinpu Township	新埔鎮",
      306 => "Guanxi Township	關西鎮",
      307 => "Qionglin Township	芎林鄉",
      308 => "Baoshan Township	寶山鄉",
      310 => "Zhudong Township	竹東鎮",
      311 => "Wufeng Township	五峰鄉",
      312 => "Hengshan Township	橫山鄉",
      313 => "Jianshi Township	尖石鄉",
      314 => "Beipu Township	北埔鄉",
      315 => "Emei Township	峨眉鄉",
      # Taoyuan City
      320 => "Zhongli District	中壢區",
      324 => "Pingzhen District	平鎮區",
      325 => "Longtan District	龍潭區",
      326 => "Yangmei District	楊梅區",
      327 => "Xinwu District	新屋區",
      328 => "Guanyin District	觀音區",
      330 => "Taoyuan District	桃園區",
      333 => "Guishan District	龜山區",
      334 => "Bade District	八德區",
      335 => "Daxi District	大溪區",
      336 => "Fuxing District	復興區",
      337 => "Dayuan District	大園區",
      338 => "Luzhu District	蘆竹區",
      # Miaoli County
      350 => "Zhunan Township	竹南鎮",
      351 => "Toufen Township	頭份鎮",
      352 => "Sanwan Township	三灣鄉",
      353 => "Nanzhuang Township	南庄鄉",
      354 => "Shitan Township	獅潭鄉",
      356 => "Houlong Township	後龍鎮",
      357 => "Tongxiao Township	通霄鎮",
      358 => "Yuanli Township	苑裡鎮",
      360 => "Miaoli City	苗栗市",
      361 => "Zaoqiao Township	造橋鄉",
      362 => "Touwu Township	頭屋鄉",
      363 => "Gongguan Township	公館鄉",
      364 => "Dahu Township	大湖鄉",
      365 => "Tai'an Township	泰安鄉",
      366 => "Tongluo Township	銅鑼鄉",
      367 => "Sanyi Township	三義鄉",
      368 => "Xihu Township	西湖鄉",
      369 => "Zhuolan Township	卓蘭鎮",
      # 4 – Taichung
      # Taichung City
      400 => "Central District	中區",
      401 => "East District	東區",
      402 => "South District	南區",
      403 => "West District	西區",
      404 => "North District	北區",
      406 => "Beitun District	北屯區",
      407 => "Xitun District	西屯區",
      408 => "Nantun District	南屯區",
      411 => "Taiping District	太平區",
      412 => "Dali District	大里區",
      413 => "Wufeng District	霧峰區",
      414 => "Wuri District	烏日區",
      420 => "Fengyuan District	豐原區",
      421 => "Houli District	后里區",
      422 => "Shigang District	石岡區",
      423 => "Dongshi District	東勢區",
      424 => "Heping District	和平區",
      426 => "Xinshe District	新社區",
      427 => "Tanzi District	潭子區",
      428 => "Daya District	大雅區",
      429 => "Shengang District	神岡區",
      432 => "Dadu District	大肚區",
      433 => "Shalu District	沙鹿區",
      434 => "Longjing District	龍井區",
      435 => "Wuqi District	梧棲區",
      436 => "Qingshui District	清水區",
      437 => "Dajia District	大甲區",
      438 => "Waipu District	外埔區",
      439 => "Da'an District	大安區",

      # 5 – Changhua, Nantou
      # Changhua County
      500 => "Changhua City	彰化市",
      502 => "Fenyuan Township	芬園鄉",
      503 => "Huatan Township	花壇鄉",
      504 => "Xiushui Township	秀水鄉",
      505 => "Lukang Township	鹿港鎮",
      506 => "Fuxing Township	福興鄉",
      507 => "Xianxi Township	線西鄉",
      508 => "Hemei Township	和美鎮",
      509 => "Shengang Township	伸港鄉",
      510 => "Yuanlin Township	員林鎮",
      511 => "Shetou Township	社頭鄉",
      512 => "Yongjing Township	永靖鄉",
      513 => "Puxin Township	埔心鄉",
      514 => "Xihu Township	溪湖鎮",
      515 => "Dacun Township	大村鄉",
      516 => "Puyan Township	埔鹽鄉",
      520 => "Tianzhong Township	田中鎮",
      521 => "Beidou Township	北斗鎮",
      522 => "Tianwei Township	田尾鄉",
      523 => "Pitou Township	埤頭鄉",
      524 => "Xizhou Township	溪州鄉",
      525 => "Zhutang Township	竹塘鄉",
      526 => "Erlin Township	二林鎮",
      527 => "Dacheng Township	大城鄉",
      528 => "Fangyuan Township	芳苑鄉",
      530 => "Ershui Township	二水鄉",
      # Nantou County
      540 => "Nantou City	南投市",
      541 => "Zhongliao Township	中寮鄉",
      542 => "Caotun Township	草屯鎮",
      544 => "Guoxing Township	國姓鄉",
      545 => "Puli Township	埔里鎮",
      546 => "Ren'ai Township	仁愛鄉",
      551 => "Mingjian Township	名間鄉",
      552 => "Jiji Township	集集鎮",
      553 => "Shuili Township	水里鄉",
      555 => "Yuchi Township	魚池鄉",
      556 => "Xinyi Township	信義鄉",
      557 => "Zhushan Township	竹山鎮",
      558 => "Lugu Township	鹿谷鄉",

      # 6 – Chiayi, Yunlin
      # Chiayi City
      600 => "East District	東區",
      600 => "West District	西區",
      # Chiayi County
      602 => "Fanlu Township	番路鄉",
      603 => "Meishan Township	梅山鄉",
      604 => "Zhuqi Township	竹崎鄉",
      605 => "Alishan Township	阿里山鄉",
      606 => "Zhongpu Township	中埔鄉",
      607 => "Dapu Township	大埔鄉",
      608 => "Shuishang Township	水上鄉",
      611 => "Lucao Township	鹿草鄉",
      612 => "Taibao City	太保市",
      613 => "Puzi City	朴子市",
      614 => "Dongshi Township	東石鄉",
      615 => "Liujiao Township	六腳鄉",
      616 => "Xingang Township	新港鄉",
      621 => "Minxiong Township	民雄鄉",
      622 => "Dalin Township	大林鎮",
      623 => "Xikou Township	溪口鄉",
      624 => "Yizhu Township	義竹鄉",
      625 => "Budai Township	布袋鎮",
      # Yunlin County
      630 => "Dounan Township	斗南鎮",
      631 => "Dapi Township	大埤鄉",
      632 => "Huwei Township	虎尾鎮",
      633 => "Tuku Township	土庫鎮",
      634 => "Baozhong Township	褒忠鄉",
      635 => "Dongshi Township	東勢鄉",
      637 => "Lunbei Township	崙背鄉",
      638 => "Mailiao Township	麥寮鄉",
      640 => "Douliu City	斗六市",
      643 => "Linnei Township	林內鄉",
      654 => "Sihu Township	四湖鄉",
      636 => "Taixi Township	臺西鄉",
      646 => "Gukeng Township	古坑鄉",
      647 => "Citong Township	莿桐鄉",
      648 => "Xiluo Township	西螺鎮",
      649 => "Erlun Township	二崙鄉",
      651 => "Beigang Township	北港鎮",
      652 => "Shuilin Township	水林鄉",
      653 => "Kouhu Township	口湖鄉",
      655 => "Yuanchang Township	元長鄉",
      # 7 – Tainan
      # Tainan City
      700 => "West Central District	中西區",
      701 => "East District	東區",
      702 => "South District	南區",
      704 => "North District	北區",
      708 => "Anping District	安平區",
      709 => "Annan District	安南區",
      710 => "Yongkang District	永康區",
      711 => "Guiren District	歸仁區",
      712 => "Xinhua District	新化區",
      713 => "Zuozhen District	左鎮區",
      714 => "Yujing District	玉井區",
      715 => "Nanxi District	楠西區",
      716 => "Nanhua District	南化區",
      717 => "Rende District	仁德區",
      718 => "Guanmiao District	關廟區",
      719 => "Longqi District	龍崎區",
      720 => "Guantian District	官田區",
      721 => "Madou District	麻豆區",
      722 => "Jiali District	佳里區",
      723 => "Xigang District	西港區",
      724 => "Qigu District	七股區",
      725 => "Jiangjun District	將軍區",
      726 => "Xuejia District	學甲區",
      727 => "Beimen District	北門區",
      730 => "Xinying District	新營區",
      731 => "Houbi District	後壁區",
      732 => "Baihe District	白河區",
      733 => "Dongshan District	東山區",
      734 => "Liujia District	六甲區",
      735 => "Xiaying District	下營區",
      736 => "Liuying District	柳營區",
      737 => "Yanshui District	鹽水區",
      741 => "Shanhua District	善化區",
      742 => "Danei District	大內區",
      743 => "Shanshang District	山上區",
      744 => "Xinshi District	新市區",
      745 => "Anding District	安定區",

      # 8 – Kaohsiung, Kinmen, Penghu
      # Kaohsiung City
      800 => "Xinxing District	新興區",
      801 => "Qianjin District	前金區",
      802 => "Lingya District	苓雅區",
      803 => "Yancheng District	鹽埕區",
      804 => "Gushan District	鼓山區",
      805 => "Qijin District	旗津區",
      806 => "Qianzhen District	前鎮區",
      807 => "Sanmin District	三民區",
      811 => "Nanzi District	楠梓區",
      812 => "Xiaogang District	小港區",
      813 => "Zuoying District	左營區",
      814 => "Renwu District	仁武區",
      815 => "Dashe District	大社區",
      817 => "Dongsha Islands	東沙群島",
      819 => "Nansha Islands	南沙群島",
      820 => "Gangshan District	岡山區",
      821 => "Luzhu District	路竹區",
      822 => "Alian District	阿蓮區",
      823 => "Tianliao District	田寮區",
      824 => "Yanchao District	燕巢區",
      825 => "Qiaotou District	橋頭區",
      826 => "Ziguan District	梓官區",
      827 => "Mituo District	彌陀區",
      828 => "Yong'an District	永安區",
      829 => "Hunei District	湖內區",
      830 => "Fengshan District	鳳山區",
      831 => "Daliao District	大寮區",
      832 => "Linyuan District	林園區",
      833 => "Niaosong District	鳥松區",
      840 => "Dashu District	大樹區",
      842 => "Qishan District	旗山區",
      843 => "Meinong District	美濃區",
      844 => "Liugui District	六龜區",
      845 => "Neimen District	內門區",
      846 => "Shanlin District	杉林區",
      847 => "Jiaxian District	甲仙區",
      848 => "Taoyuan District	桃源區",
      849 => "Namaxia District	那瑪夏區",
      851 => "Maolin District	茂林區",
      852 => "Qieding District	茄萣區",
      # Penghu County
      880 => "Magong City	馬公市",
      881 => "Xiyu Township	西嶼鄉",
      882 => "Wang'an Township	望安鄉",
      883 => "Qimei Township	七美鄉",
      884 => "Baisha Township	白沙鄉",
      885 => "Huxi Township	湖西鄉",
      # Kinmen County
      890 => "Jinsha Township	金沙鎮",
      891 => "Jinhu Township	金湖鎮",
      892 => "Jinning Township	金寧鄉",
      893 => "Jincheng Township	金城鎮",
      894 => "Lieyu Township	烈嶼鄉",
      896 => "Wuqiu Township	烏坵鄉",

      # 9 – Hualien, Pingtung, Taitung
      # Pingtung County
      900 => "Pingtung City	屏東市",
      901 => "Sandimen Township	三地門鄉",
      902 => "Wutai Township	霧臺鄉",
      903 => "Majia Township	瑪家鄉",
      904 => "Jiuru Township	九如鄉",
      905 => "Ligang Township	里港鄉",
      906 => "Gaoshu Township	高樹鄉",
      907 => "Yanpu Township	鹽埔鄉",
      908 => "Changzhi Township	長治鄉",
      909 => "Linluo Township	麟洛鄉",
      911 => "Zhutian Township	竹田鄉",
      912 => "Neipu Township	內埔鄉",
      913 => "Wandan Township	萬丹鄉",
      920 => "Chaozhou Township	潮州鎮",
      921 => "Taiwu Township	泰武鄉",
      922 => "Laiyi Township	來義鄉",
      923 => "Wanluan Township	萬巒鄉",
      924 => "Kanding Township	崁頂鄉",
      925 => "Xinpi Township	新埤鄉",
      926 => "Nanzhou Township	南州鄉",
      927 => "Linbian Township	林邊鄉",
      928 => "Donggang Township	東港鎮",
      929 => "Liuqiu Township	琉球鄉",
      931 => "Jiadong Township	佳冬鄉",
      932 => "Xinyuan Township	新園鄉",
      940 => "Fangliao Township	枋寮鄉",
      941 => "Fangshan Township	枋山鄉",
      942 => "Chunri Township	春日鄉",
      943 => "Shizi Township	獅子鄉",
      944 => "Checheng Township	車城鄉",
      945 => "Mudan Township	牡丹鄉",
      946 => "Hengchun Township	恆春鎮",
      947 => "Manzhou Township	滿州鄉",
      # Taitung County
      950 => "Taitung City	臺東市",
      951 => "Lüdao Township	綠島鄉",
      952 => "Lanyu Township	蘭嶼鄉",
      953 => "Yanping Township	延平鄉",
      954 => "Beinan Township	卑南鄉",
      955 => "Luye Township	鹿野鄉",
      956 => "Guanshan Township	關山鎮",
      957 => "Haiduan Township	海端鄉",
      958 => "Chishang Township	池上鄉",
      959 => "Donghe Township	東河鄉",
      961 => "Chenggong Township	成功鎮",
      962 => "Changbin Township	長濱鄉",
      963 => "Taimali Township	太麻里鄉",
      964 => "Jinfeng Township	金峰鄉",
      965 => "Dawu Township	大武鄉",
      966 => "Daren Township	達仁鄉",
      # Hualien County
      970 => "Hualien City	花蓮市",
      971 => "Xincheng Township	新城鄉",
      972 => "Xiulin Township	秀林鄉",
      973 => "Ji'an Township	吉安鄉",
      974 => "Shoufeng Township	壽豐鄉",
      975 => "Fenglin Township	鳳林鎮",
      976 => "Guangfu Township	光復鄉",
      977 => "Fengbin Township	豐濱鄉",
      978 => "Ruisui Township	瑞穗鄉",
      979 => "Wanrong Township	萬榮鄉",
      981 => "Yuli Township	玉里鎮",
      982 => "Zhuoxi Township	卓溪鄉",
      983 => "Fuli Township	富里鄉",
    }
  end
end
